# Generated by Django 5.2.4 on 2025-07-26 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operando1', models.FloatField()),
                ('operando2', models.FloatField()),
                ('operador', models.CharField(choices=[('+', 'soma'), ('-', 'subtração'), ('*', 'multiplicação'), ('/', 'divisão')], max_length=1)),
                ('resultado', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
