# Generated by Django 5.2.4 on 2025-07-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='operador',
            field=models.CharField(choices=[('+', 'soma'), ('-', 'subtração'), ('x', 'multiplicação'), ('÷', 'divisão')], max_length=1),
        ),
    ]
