# Generated by Django 5.2.4 on 2025-07-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portal', '0002_alter_operacao_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='operador',
            field=models.CharField(choices=[('+', 'soma'), ('-', 'subtração'), ('*', 'multiplicação'), ('/', 'divisão')], max_length=1),
        ),
    ]
